RSpec/DescribeClass:
  Description: 'Check that the first argument to the top level describe is the tested class or module.'
  Enabled: true

RSpec/DescribedClass:
  Description: 'Use `described_class` for tested class / module'
  Enabled: true

RSpec/DescribeMethod:
  Description: 'Checks that the second argument to top level describe is the tested method name.'
  Enabled: true

RSpec/ExampleWording:
  Description: 'Do not use should when describing your tests.'
  Enabled: true
  CustomTransform:
    be: is
    have: has
    not: does not
  IgnoredWords: []


RSpec/MultipleDescribes:
  Description: 'Checks for multiple top level describes.'
  Enabled: true

RSpec/InstanceVariable:
  Description: 'Checks for the usage of instance variables.'
  Enabled: true

RSpec/FilePath:
  Description: 'Checks the file and folder naming of the spec file.'
  Enabled: true
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec

RSpec/VerifiedDoubles:
  Description: 'Prefer using verifying doubles over normal doubles.'
  Enabled: false

RSpec/LineBetweenContexts:
  Description: 'Checks that context blocks are separated by an empty line'
  Enabled: false
